/* Autogenerated by png2wx.pl on Sat Jun 10 15:50:09 2017 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_logo;
extern wxBitmap *_img_logo_pi;

#endif /* ICONS_H */
