#ifndef __minimalwindow__
#define __minimalwindow__

/**
@file
Subclass of minWinDef, which is generated by wxFormBuilder.
*/

#include "minimalgui.h"

//// end generated include

/** Implementing minWinDef */
class minimalWindow : public minWinDef
{
	public:
		/** Constructor */
		minimalWindow( wxWindow* parent );
	//// end generated class members
	
};

#endif // __minimalwindow__
